---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ansd/main-bosh-docker-build-essential

inputs:
- name: ruby-2.4
- name: rubygems
- name: yaml
- name: ruby-release
- name: stemcell

outputs:
- name: ruby-release
  path: bumped-ruby-release

run:
  path: ruby-release/ci/tasks/bump.sh

params:
  PRIVATE_YAML: ~
