---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ansd/main-bosh-docker-build-essential

inputs:
- name: ruby-release
- name: semver

outputs:
- name: version-tag
- name: bumped-semver
- name: finalized-release

params:
  PRIVATE_YML: ~

run:
  path: ruby-release/ci/tasks/finalize.sh
