---

jobs:
- name: test
  serial: true
  plan:
  - aggregate:
    - get: ruby-release
      trigger: true
    - get: bosh-src
    - get: stemcell
      trigger: true
  - task: test
    privileged: true
    file: ruby-release/ci/tasks/test.yml
    params:
      RUBY_RELEASE_DIR: ruby-release

- name: bump
  serial: true
  plan:
  - aggregate:
    - get: ruby-2.4
      trigger: true
    - get: rubygems-2.7
      trigger: true
    - get: yaml-0.1
      trigger: true
    - get: bosh-src
    - get: ruby-release
    - get: stemcell
    - get: semver
  - task: bump
    file: ruby-release/ci/tasks/bump.yml
    params:
      PRIVATE_YML: ((s3_private_yml))
      RUBY_VERSION: "2.4"
      RUBYGEMS_VERSION: "2.7"
      LIBYAML_VERSION: "0.1"
  - task: test-bumped
    privileged: true
    file: ruby-release/ci/tasks/test-bumped.yml
    params:
      RUBY_RELEASE_DIR: bumped-ruby-release
  - task: finalize
    file: ruby-release/ci/tasks/finalize.yml
    params:
      PRIVATE_YML: ((s3_private_yml))
  - aggregate:
    - put: semver
      params:
        file: bumped-semver/version
    - put: ruby-release
      params:
        rebase: true
        repository: finalized-release
        tag: version-tag/tag-name
        annotate: version-tag/annotate-msg

resources:
- name: bosh-src
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh.git
    branch: master

- name: ruby-release
  type: git
  source:
    uri: https://github.com/ansd/ruby-release.git
    branch: ci
    username: openstack-cpi
    password: ((github-token))

- name: stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-xenial-go_agent

- name: semver
  type: semver
  source:
    bucket: bosh-packages-ruby-release-blobs
    key: version
    initial_version: 7.7.7
    access_key_id: ((s3_aws_access_key_id))
    secret_access_key: ((s3_aws_secret_access_key))

- name: rubygems-2.7
  type: dynamic-metalink
  tags: ((worker_tags))
  source:
    version: "2.7.x"
    version_check: |
     git ls-remote --tags https://github.com/rubygems/rubygems.git \
       | cut -f2 \
       | grep -v '\^{}' \
       | grep -E '^refs/tags/.+$' \
       | sed  -E 's/^refs\/tags\/(.+)$/\1/'  \
       | sed  's/^v//' \
       | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$'
    metalink_get: |
      export name="rubygems-${version}.tgz"
      export url="https://rubygems.org/rubygems/rubygems-${version}.tgz"
      export size=$( curl --silent --head "$url" | grep Content-Length | awk '{ print $2 }' | tr -cd '[:digit:]' )
      jq -n '
      {
       "files": [
        {
         "name": env.name,
         "urls": [ { "url": env.url } ],
         "size": env.size | tonumber
        }
       ]
      }'

- name: yaml-0.1
  type: dynamic-metalink
  tags: ((worker_tags))
  source:
    version: "0.1.x"
    version_check: |
     git ls-remote --tags https://github.com/yaml/libyaml.git \
       | cut  -f2 \
       | grep -v '\^{}' \
       | grep -E '^refs/tags/.+$' \
       | sed  -E 's/^refs\/tags\/(.+)$/\1/'  \
       | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$'
    metalink_get: |
      export name="yaml-${version}.tar.gz"
      export url="http://pyyaml.org/download/libyaml/yaml-${version}.tar.gz"
      export size=$( curl --silent --head "$url" | grep Content-Length | awk '{ print $2 }' | tr -cd '[:digit:]' )
      jq -n '
      {
       "files": [
        {
         "name": env.name,
         "urls": [ { "url": env.url } ],
         "size": env.size | tonumber
        }
       ]
      }'

- name: ruby-2.4
  type: dynamic-metalink
  tags: ((worker_tags))
  source:
    version: "2.4.x"
    version_check: |
      curl --silent --location https://raw.githubusercontent.com/postmodern/ruby-versions/master/ruby/stable.txt
    metalink_get: |
      export name="ruby-${version}.tar.gz"
      export url="http://cache.ruby-lang.org/pub/ruby/${name}"
      export sha256="$(curl --silent --location https://raw.githubusercontent.com/postmodern/ruby-versions/master/ruby/checksums.sha256 | grep ruby-${version}.tar.gz | awk {'print $1'})"
      export size="$(curl --silent --head "$url" | grep -i Content-Length | awk '{ print $2 }' | tr -cd '[:digit:]')"
      jq -n '
      {
       "files": [
        {
         "name": env.name,
         "urls": [ { "url": env.url } ],
         "hashes": [{ "type": "sha-256", "hash": env.sha256 }],
         "size": env.size | tonumber
        }
       ]
      }'

resource_types:
- name: dynamic-metalink
  type: docker-image
  source:
    repository: dpb587/dynamic-metalink-resource
